//event-type list
//event-type list
final List<String> currencyTypeList = [
  "USD",
  "NGN",
];

final List<Map<String, String>> eventTypeList = [
  {"id": "Corporate_Event", "name": "Corporate Event"},
  {"id": "Seminar", "name": "Seminar"},
  {"id": "Conference", "name": "Conference"},
  {"id": "Trade_show", "name": "Trade Show"},
  {"id": "Workshops", "name": "Workshops"},
  {"id": "Summit", "name": "Summit"},
  {"id": "Business", "name": "Business"},
  {"id": "Social_Events", "name": "Social Events"},
  {"id": "Picnic", "name": "Picnic"},
  {"id": "Reunion", "name": "Reunion"},
  {"id": "Themed_Party", "name": "Themed Party"},
  {"id": "Wedding", "name": "Wedding"},
  {"id": "Traditional_Wedding", "name": "Traditional Wedding"},
  {"id": "Engagement_Ceremony", "name": "Engagement Ceremony"},
  {"id": "Child_Naming_Ceremony", "name": "Child Naming Ceremony"},
  {"id": "Baby_Shower", "name": "Baby Shower"},
  {"id": "Bridal_Shower", "name": "Bridal Shower"},
  {"id": "Bachelors_Eve", "name": "Bachelors Eve"},
  {"id": "Comedy", "name": "Comedy"},
  {"id": "Fashion_Show", "name": "Fashion Show"},
  {"id": "Birthday_Party", "name": "Birthday Party"},
  {"id": "Others", "name": "Others"},
  {"id": "College_Events", "name": "College Events"},
  {"id": "Movie_Night", "name": "Movie Night"},
  {"id": "Food_Drive", "name": "Food Drive"},
  {"id": "Service_Project", "name": "Service Project"},
  {"id": "Dodgeball_Tournament", "name": "Dodgeball Tournament"},
  {"id": "Bake_Sale", "name": "Bake Sale"},
  {"id": "Charity_Run", "name": "Charity Run"},
  {"id": "Rock_Climbing", "name": "Rock Climbing"},
  {"id": "Laser_Tag", "name": "Laser Tag"},
  {"id": "Karaoke_Night", "name": "Karaoke Night"},
  {"id": "Bowling", "name": "Bowling"},
  {"id": "Volunteer", "name": "Volunteer"},
  {"id": "Museum", "name": "Museum"},
  {"id": "Paint_Night", "name": "Paint Night"},
  {"id": "Theatre_Production", "name": "Theatre Production"},
  {"id": "Talent_Show", "name": "Talent Show"},
  {"id": "Science_Fair", "name": "Science Fair"},
  {"id": "Pizza_Party", "name": "Pizza Party"},
  {"id": "Yoga_Class", "name": "Yoga Class"},
  {"id": "TEDx_Speakers", "name": "TEDx Speakers"},
  {"id": "Sports_Competition", "name": "Sports Competition"},
  {"id": "Celebrity_Guest", "name": "Celebrity Guest"},
  {"id": "Alumni_Speakers", "name": "Alumni Speakers"},
  {"id": "Pajama_Party", "name": "Pajama Party"},
  {"id": "Cooking_Lesson", "name": "Cooking Lesson"},
  {"id": "Book_Club", "name": "Book Club"},
  {"id": "Photo_Booth", "name": "Photo Booth"},
  {"id": "Ice_Cream_Sundae_Bar", "name": "Ice Cream Sundae Bar"},
  {"id": "Comedy_Night", "name": "Comedy Night"},
  {"id": "Professional_Headshots", "name": "Professional Headshots"},
  {"id": "Christmas_Party", "name": "ChristmasParty"},
  {"id": "Car_Wash", "name": "Car Wash"},
  {"id": "Yard_Sales", "name": "Yard Sales"},
  {"id": "Matriculation", "name": "Matriculation"},
  {"id": "Graduation_Party", "name": "Graduation Party"},
  {"id": "Arts_And_Crafts", "name": "Arts And Crafts"},
  {"id": "Virtual_Events", "name": "Virtual Events"},
  {"id": "Webinars", "name": "Webinars"},
  {"id": "Workshop", "name": "Workshop"},
  {"id": "Training", "name": "Training"},
  {"id": "Religious_Event", "name": "Religious Event"},
  {"id": "Vigil", "name": "Vigil"},
  {"id": "Praise_Concert", "name": "Praise Concert"},
  {"id": "Prayer_Meeting", "name": "Prayer Meeting"},
  {"id": "Popup_Event", "name": "Popup Event"},
  {"id": "Boutique_Shops", "name": "Boutique Shops"},
  {"id": "Food_Collaboration", "name": "Food Collaboration"},
  {"id": "Exercise_Class", "name": "Exercise Class"},
  {"id": "Fundraising_Event", "name": "Fundraising Event"},
  {"id": "NGO", "name": "NGO"},
  {"id": "Auction", "name": "Auction"},
  {"id": "Sponsored_Sporting_Event", "name": "Sponsored Sporting Event"},
  {"id": "Gala_Dinner", "name": "Gala Dinner"},
  {"id": "Festival", "name": "Festival"},
  {"id": "Music_Festival", "name": "Music Festival"},
  {"id": "Food_Festival", "name": "Food Festival"},
  {"id": "Carnival", "name": "Carnival"},
  {"id": "Community_Event", "name": "Community Event"},
  {"id": "Street_Party", "name": "Street Party"},
  {"id": "Sanitation", "name": "Sanitation"},
];
